# Docker Compose file for Media Server Suite
# Suite includes Sonarr, Radarr, NZBGET, Portainer, etc.
# Created: 2020-12-19
# Updated: 2021-03-01

version: '3.3'


services:


    autoscan:
      container_name: autoscan
      ports:
          - '3030:3030'
      environment:
          - PUID=1000
          - PGID=129
          - UMASK=002
          - TZ=America/Vancouver
          - PLEX_LOGIN=
          - PLEX_PASSWORD=
      volumes:
          - '/home/thor/.config/autoscan:/config'
      image: cr.hotio.dev/hotio/autoscan

    # NZBGET Block
    nzbget:
      image: hotio/nzbget:testing
      container_name: nzbget
      restart: unless-stopped
      ports:
        - 6789:6789
      #network_mode: host
      environment:
        - PUID=1000
        - PGID=129
        - UMASK=002
        - TZ=America/Vancouver
        - ARGS=
        - DEBUG=no
      volumes:
        - /home/thor/.config/nzbget:/config
        - /downloads:/data/downloads

    # RADARR Block
    radarr:
      image: hotio/radarr:nightly
      container_name: radarr
      depends_on:
        - "nzbget"
      restart: unless-stopped
      ports:
        - 7878:7878
      environment:
        - PUID=1000
        - PGID=129
        - UMASK=002
        - TZ=America/Vancouver
        - ARGS=
        - DEBUG=no
      volumes:
        - /home/thor/.config/radarr:/config
        - /downloads:/data/downloads
        - /gmedia:/data/media

    # SONARR Block
    sonarr:
      image: hotio/sonarr:nightly
      container_name: sonarr
      depends_on:
        - "nzbget"
      restart: unless-stopped
      #network_mode: host
      ports:
        - 8989:8989
      environment:
        - PUID=1000
        - PGID=129
        - UMASK=002
        - ARGS=
        - DEBUG=no
      volumes:
        - /home/thor/.config/sonarr:/config
        - /downloads:/data/downloads:rw
        - /gmedia:/data/media:rw
    
    # TAUTULLI Block
    tautulli:
      image: tautulli/tautulli
      container_name: tautulli
      restart: unless-stopped
      ports:
        - 8181:8181
      environment:
        - PUID=1000
        - PGID=129
        - UMASK=002
      volumes:
        - /home/thor/.config/tautulli:/config
